<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('MegaAdmin '. $this->translate('Aplicação Esqueleto'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                // BEGIN STYLE CODE FOR THE CURRENT PAGE -->
                        ->prependStylesheet($this->basePath() . '/assets/plugins/jquery.jqvmap/jqvmap.css') 
                // BEGIN STYLE CODE FOR THE CURRENT PAGE -->
                // END STYLE CODE FOR THE CURRENT PAGE -->
                        ->prependStylesheet($this->basePath() . '/assets/css/twitter-bootstrap/bootstrap-responsive.css')        
                        ->prependStylesheet($this->basePath() . '/assets/css/themes/social.theme-blue.css')
                        ->prependStylesheet($this->basePath() . '/assets/plugins/jquery.simplecolorpicker/jquery.simplecolorpicker.css')        
                        ->prependStylesheet($this->basePath() . '/assets/plugins/jquery.uipro/style.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/demo.css')
                        
                // BEGIN STYLE CODES
                        ->prependStylesheet($this->basePath() . '/assets/css/social-coloredicons-buttons.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/font-awesome.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/social.plugins.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/social.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/social-jquery-ui-1.10.0.custom.css')
                        ->prependStylesheet($this->basePath() . '/assets/css/twitter-bootstrap/bootstrap.css')
                ; ?>
        
        <!--[if lt IE 9]>
        <link rel="stylesheet" type="text/css" href="/templates/social/assets/css/social-jquery.ui.1.10.0.ie.css"/>
        <![endif]-->
        
        <style>
            #justGaugeExamples{
              text-align: center;
              height: 300px;
            }
            #g1, #g2 {
              width:200px; height:160px;
              display: inline-block;
              margin-top: -5px;
              /*margin: 5px;*/
            }
          </style>
            <!-- END STYLE CODE FOR THE CURRENT PAGE -->

                <style>
              .wraper #main{
                margin-top: 40px;
              }
            </style>
    <!-- END STYLE CODES -->
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/templates/social/assets/plugins/html5shiv.js"></script>
    <![endif]-->
        
    </head>
    <body>
            <!-- BEGIN WRAPER -->
    <div class="wraper sidebar-full">
      <!-- BEGIN SIDEBAR -->
      <aside class="social-sidebar sidebar-full">
    <!-- BEGIN USER SETTINGS -->
    <div class="user-settings">
        <div class="arrow"></div>
        <h3 class="user-settings-title">Settings shortcuts</h3>
        <div class="user-settings-content">
            <a href="pages/basic-user-profile.html">
                <div class="icon">
                    <i class="icon-user"></i>
                </div>
                <div class="title">My Profile</div>
                <div class="content">View your profile</div>
            </a>
            <a href="pages/chat-inbox.html">
                <div class="icon">
                    <i class="icon-envelope"></i>
                </div>
                <div class="title">View Messages</div>
                <div class="content">You have <strong>17</strong> new messages</div>
            </a>
            <a href="#view-pending-tasks">
                <div class="icon">
                    <i class="icon-tasks"></i>
                </div>

                <div class="title">View Tasks</div>
                <div class="content">You have <strong>8</strong> pending tasks</div>
            </a>
        </div>
        <div class="user-settings-footer">
            <a href="#more-settings">See more settings</a>
        </div>
    </div>
    <!-- END USER SETTINGS -->
    <!-- BEGIN SIDEBAR CONTENT -->
    <div class="social-sidebar-content">
        <div class="scrollable">
            <!-- BEGIN USER INFO SECTION -->
            <div class="user">
              <img class="avatar" width="25" height="25" src="../assets/img/avatar-30.png" alt="Julio Marquez">
              <span>Julio Marquez</span>
              <i class="icon-user"></i>
            </div>
            <!-- END USER INFO SECTION -->
            <!-- BEGIN NAVIGATION CONTROLS -->
              <div class="navigation-sidebar">
                <i class="switch-sidebar-icon icon-align-justify"></i>
                              </div>
            <!-- END NAVIGATION CONTROLS -->
            <!-- BEGIN SEARCH SIDEBAR FORM -->
            <div class="search-sidebar">
                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/search.png" alt="Search">
              

              <form class="search-sidebar-form">
                <input type="text" class="search-query input-block-level" placeholder="Search">
              </form>
            </div>
            <!-- END SEARCH SIDEBAR FORM -->
            <!-- BEGIN MENU SECTION -->
            <section class="menu">
                <!-- BEGIN ACCORDION SECTION -->
                <div class="accordion" id="accordion2">
                                                                                                                                                                            
                  <!-- BEGIN MULTI LEVEL ACCORDION GROUP -->
                                      <!-- END MULTI LEVEL ACCORDION GROUP -->


                  <!-- BEGIN ACCORDION GROUP -->
                  <div class="accordion-group active">
                    <!-- BEGIN ACCORDION HEADING -->
                    <div class="accordion-heading">
                                              <a class="accordion-toggle opened" href="/">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/home.png" alt="Dashboard">
                      

                    <span>Dashboard</span><span class="badge">10</span>
                        </a>
                    </div>
                    <!-- END ACCORDION HEADING -->
                                      </div>
                  <!-- END ACCORDION GROUP -->
                                                                                                                                                                            
                  <!-- BEGIN MULTI LEVEL ACCORDION GROUP -->
<!--                                            <div class="accordion-group">
   BEGIN ACCORDION HEADING 
  <div class="accordion-heading">
      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse-multi-level">
          <i class="icon-sitemap icon-2"></i>
          <span>Multi Level </span><span class="arrow"></span>
      </a>
  </div>
   END ACCORDION HEADING 
   BEGIN MENU LIST ITEMS 
   You need to add the class .sub-menu whe you want more than 2 levels 
  <ul id="collapse-multi-level" class="accordion-body nav nav-list collapse sub-menu">
    <li>
         Those sub-multi-level trigers must have the
              property data-toggle="sub-menu-collapse"
              and the property data-target with a selector
              the refers the element that this collapses
        
        <a href="#" data-toggle="sub-menu-collapse" data-target="#collapse-2-level">
            <span>4-Level</span>
            <span class="arrow"></span>
        </a>
    </li>
     BEGIN 3-LEVEL 
     The class .collapse is important 
    <ul id="collapse-2-level" class="nav nav-list collapse">
        <li>
             Those sub-multi-level trigers must have the
                property data-toggle="sub-menu-collapse" and
                the property data-target with a selector the
                refers the element that this collapses
            
            <a href="#" data-toggle="sub-menu-collapse" data-target="#collapse-3-level">
              <span>Sub Element 1</span>
              <span class="arrow"></span>
            </a>
        </li>
         BEGIN 4-LEVEL 
         The class .collapse is important 
        <ul id="collapse-3-level" class="nav nav-list collapse">
            <li><a href="#">Element 1</a></li>
            <li><a href="#">Element 2</a></li>
            <li><a href="#">Element 3</a></li>
        </ul>
         END 4-LEVEL 
        <li><a href="#">Sub Element 2</a></li>
        <li><a href="#">Sub Element 3</a></li>
        <li><a href="#">Sub Element 4</a></li>
    </ul>
     END 3-LEVEL 
    <li>
       Those sub-multi-level trigers must have the
          property data-toggle="sub-menu-collapse" and
          the property data-target with a selector the
          refers the element that this collapses
      
      <a href="#" data-toggle="sub-menu-collapse" data-target="#collapse-2-level2">
        <span>3-Level</span>
        <span class="arrow"></span>
      </a>
    </li>
     BEGIN 3-LEVEL 
     The class .collapse is important 
    <ul id="collapse-2-level2" class="nav nav-list collapse">
        <li>
            <a href="#">
            <span>Sub Element 1</span>
        </a>
        </li>
        <li><a href="#">Sub Element 2</a></li>
    </ul>
     END 3-LEVEL 
    <li><a href="#">2-Level</a></li>
   </ul>
 END MENU LIST ITEMS 
</div>-->
                                      <!-- END MULTI LEVEL ACCORDION GROUP -->


                  <!-- BEGIN ACCORDION GROUP -->
                  <div class="accordion-group ">
                    <!-- BEGIN ACCORDION HEADING -->
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-cadastro">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/database.png" alt="UI Elements">
                      

                    <span>Cadastro</span><span class="arrow"></span>
                        </a>
                    </div>
                    <!-- END ACCORDION HEADING -->
                                            <!-- BEGIN MENU LIST ITEMS -->
                        <ul id="collapse-cadastro" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="/contabil/home">Empresa</a></li>
                                                            <li><a href="/">Usuário</a></li>
                                                    </ul>
                        <!-- END MENU LIST ITEMS -->
                                      </div>
                  <!-- END ACCORDION GROUP -->
                  
                  <!-- BEGIN ACCORDION GROUP -->
                  <div class="accordion-group ">
                    <!-- BEGIN ACCORDION HEADING -->
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-publicar">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/database.png" alt="UI Elements">
                      

                    <span>Publicar</span><span class="arrow"></span>
                        </a>
                    </div>
                    <!-- END ACCORDION HEADING -->
                                            <!-- BEGIN MENU LIST ITEMS -->
                        <ul id="collapse-publicar" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="/">Guia de imposto</a></li>
                                                            <li><a href="/">Honorário</a></li>
                                                            <li><a href="/">Documentos</a></li>
                                                    </ul>
                        <!-- END MENU LIST ITEMS -->
                                      </div>
                  <!-- END ACCORDION GROUP -->
                  
                  <!-- BEGIN ACCORDION GROUP -->
                  <div class="accordion-group ">
                    <!-- BEGIN ACCORDION HEADING -->
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-importar">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/database.png" alt="UI Elements">
                      

                    <span>Importar</span><span class="arrow"></span>
                        </a>
                    </div>
                    <!-- END ACCORDION HEADING -->
                                            <!-- BEGIN MENU LIST ITEMS -->
                        <ul id="collapse-importar" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="/">Empresa</a></li>
                                                            <li><a href="/">Movimento</a></li>
                                                    </ul>
                        <!-- END MENU LIST ITEMS -->
                                      </div>
                  <!-- END ACCORDION GROUP -->
                                                                                                                                                                            
                  <!-- BEGIN MULTI LEVEL ACCORDION GROUP -->
                                      <!-- END MULTI LEVEL ACCORDION GROUP -->


                  <!-- BEGIN ACCORDION GROUP -->
<!--                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-form-stuff">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/sitemap.png" alt="Form Stuff">
                      

                    <span>Form Stuff </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-form-stuff" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="form-stuff/elements.html">Form elements</a></li>
                                                            <li><a href="form-stuff/validation.html">Form validation</a></li>
                                                            <li><a href="form-stuff/wizards.html">Wizards</a></li>
                                                            <li><a href="form-stuff/wysiwyg.html">WYSIWYG</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " href="charts.html">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/statistics.png" alt="Charts">
                      

                    <span>Charts </span><span class="badge">6</span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group  hidden-desktop">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-layouts">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/archives.png" alt="Layouts">
                      

                    <span>Layouts </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-layouts" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="layouts/blank-page.html">Blank Page</a></li>
                                                            <li><a href="layouts/full-width-page.html">Full Width Page</a></li>
                                                            <li><a href="layouts/font-icon-sidebar.html">Font Icon Sidebar</a></li>
                                                            <li><a href="layouts/expanded-sidebar.html">Expanded Sidebar</a></li>
                                                            <li><a href="layouts/sticky-footer.html">Sticky footer</a></li>
                                                            <li><a href="layouts/auto-hide-sidebar.html">Auto-Hide Sidebar</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group  hidden-desktop">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-pages">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/star.png" alt="Pages">
                      

                    <span>Pages </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-pages" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="pages/facebook-timeline.html">Facebook Timeline</a></li>
                                                            <li><a href="pages/historical-timeline.html">Historical Timeline</a></li>
                                                            <li><a href="pages/basic-user-profile.html">Basic User Profile</a></li>
                                                            <li><a href="pages/chat-inbox.html">Chat Inbox</a></li>
                                                            <li><a href="pages/pricing-tables.html">Pricing Tables</a></li>
                                                            <li><a href="pages/email-templates.html">Email Templates</a></li>
                                                            <li><a href="pages/email-inbox.html">Email Inbox</a></li>
                                                            <li><a href="pages/email-inbox-preview-pane.html">Email Inbox with Preview Pane</a></li>
                                                            <li><a href="pages/search-results.html">Search Results</a></li>
                                                            <li><a href="pages/blog-category.html">Blog Category</a></li>
                                                            <li><a href="pages/blog-page.html">Blog Page</a></li>
                                                            <li><a href="pages/contact-us.html">Contact Us</a></li>
                                                            <li><a href="pages/404-page.html">404 Page</a></li>
                                                            <li><a href="pages/500-page.html">500 Page</a></li>
                                                            <li><a href="pages/invoice.html">Invoice</a></li>
                                                            <li><a href="pages/login.html">Login</a></li>
                                                            <li><a href="pages/faq.html">FAQ</a></li>
                                                            <li><a href="pages/features-page.html">Features Page</a></li>
                                                            <li><a href="pages/shop-category.html">Shop Category</a></li>
                                                            <li><a href="pages/shop-index.html">Shop Index</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-tables">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/invoice.png" alt="Tables">
                      

                    <span>Tables </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-tables" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="tables/basic.html">Basic tables</a></li>
                                                            <li><a href="tables/dynamic.html">Dynamic tables</a></li>
                                                            <li><a href="tables/responsive.html">Responsive Tables</a></li>
                                                            <li><a href="tables/jquery.html">jQuery Style</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-files-media">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/photography.png" alt="Files &amp; Media">
                      

                    <span>Files &amp; Media </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-files-media" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="files-media/gallery.html">Gallery</a></li>
                                                            <li><a href="files-media/file-uploaders.html">File Uploaders</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " href="calendar.html">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/calendar.png" alt="Calendar">
                      

                    <span>Calendar </span><span class="badge">1</span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                      </div>
                   END ACCORDION GROUP 
                                                                                                                                                                            
                   BEGIN MULTI LEVEL ACCORDION GROUP 
                                       END MULTI LEVEL ACCORDION GROUP 


                   BEGIN ACCORDION GROUP 
                  <div class="accordion-group ">
                     BEGIN ACCORDION HEADING 
                    <div class="accordion-heading">
                                              <a class="accordion-toggle " data-toggle="collapse" data-parent="#accordion2" href="#collapse-maps">
                      
                                              <img src="../assets/img/icons/stuttgart-icon-pack/32x32/world.png" alt="Maps">
                      

                    <span>Maps </span><span class="arrow"></span>
                        </a>
                    </div>
                     END ACCORDION HEADING 
                                             BEGIN MENU LIST ITEMS 
                        <ul id="collapse-maps" class="accordion-body nav nav-list collapse ">
                                                            <li><a href="maps/vector.html">Vector Maps</a></li>
                                                            <li><a href="maps/google.html">Google Maps</a></li>
                                                    </ul>
                         END MENU LIST ITEMS 
                                      </div>
                   END ACCORDION GROUP -->
                </div>
                <!-- END ACCORDION SECTION -->
                            </section>
            <!-- END MENU SECTION -->

        </div>
        <!-- BEGIN CHAT USERS LIST -->
<!--        <div class="chat-users">
          <div class="no-user">User not found</div>
          <ul class="user-list">
            <li>
                <a data-firstname="Cesar" data-lastname="Mendoza" data-status="online" data-userid="1" href="#">
                    <img src="../assets/img/people-face/user2_22.jpg" alt="">
                    <span>Cesar Mendoza</span>
                    <i class="icon-circle user-status online"></i>
                </a>
            </li>
            <li>
                <a data-firstname="Yadra" data-lastname="Abels" data-status="offline" data-userid="2" href="#">
                    <img src="../assets/img/people-face/user1_22.jpg" alt="">
                    <span>Yadra Abels</span>
                    <i class="icon-circle user-status offline"></i>
                </a>
            </li>
            <li>
                <a data-firstname="Tobei" data-lastname="Tsumura" data-status="online" data-userid="3" href="#">
                    <img src="../assets/img/people-face/user4_22.jpg" alt="">
                    <span>Tobei Tsumura</span>
                    <i class="icon-circle user-status online"></i>
                </a>
            </li>
            <li>
                <a data-firstname="John" data-lastname="Doe" data-status="offline" data-userid="4" href="#">
                    <img src="../assets/img/people-face/user3_22.jpg" alt="">
                    <span>John Doe</span>
                    <i class="icon-circle user-status offline"></i>
                </a>
            </li>
          </ul>


          <form class="user-filter">
            <div class="input-prepend open">
              <div class="btn-group dropup">
                <button class="btn dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-cog"></i>
                </button>
                <ul class="dropdown-menu pull-left">
                  <li><a href="#">Chat Sounds</a></li>
                  <li><a href="#">Advanced Settings...</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Turn Off Chat</a></li>
                </ul>
              </div>
              <input type="text" class="input-filter" placeholder="Search user...">
            </div>
          </form>
        </div>-->
        <!-- END CHAT USERS LIST -->
        </div>
    <!-- END SIDEBAR CONTENT -->
</aside>
      <!-- END SIDEBAR -->
      <header>
        <!-- BEGIN NAVBAR -->
        <nav class="navbar navbar-fixed-top social-navbar social-sm">
   <div class="navbar-inner">
     <div class="container-fluid">
       <!-- BEGIN SIDEBAR COLLAPSER -->
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".social-sidebar">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <!-- END SIDEBAR COLLAPSER -->
       <!-- BEGIN BRAND LINK -->
       <a class="brand" href="dashboard.html">
                 Social
       </a>
       <!-- END BRAND LINK -->
        <ul class="nav visible-desktop">
        <!--  -->
                                    <li class="dropdown visible-desktop ">
      <a href="#layouts" class="dropdown-toggle" data-toggle="dropdown">Layouts <b class="caret"></b></a>
      <ul class="dropdown-menu">

                    <!--  -->
                                                                              <li>
                    <a href="layouts/blank-page.html" target=&quot;_blank&quot;>Blank Page</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="layouts/full-width-page.html" target=&quot;_blank&quot;>Full Width Page</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="layouts/font-icon-sidebar.html" target=&quot;_blank&quot;>Font Icon Sidebar</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="layouts/expanded-sidebar.html" target=&quot;_blank&quot;>Expanded Sidebar</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="layouts/sticky-footer.html" target=&quot;_blank&quot;>Sticky footer</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="layouts/auto-hide-sidebar.html" target=&quot;_blank&quot;>Auto-Hide Sidebar</a>
                  </li>
                  <!--  -->
                        </ul>
    </li>
                                    <li class="dropdown visible-desktop ">
      <a href="#pages" class="dropdown-toggle" data-toggle="dropdown">Pages <b class="caret"></b></a>
      <ul class="dropdown-menu">

                    <!--  -->
                                                                              <li>
                    <a href="pages/email-templates.html">Email Templates</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="pages/search-results.html">Search Results</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="pages/invoice.html">Invoice</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="pages/login.html">Login</a>
                  </li>
                  <!--  -->
                          <!--  -->
                                                                              <li>
                    <a href="pages/faq.html">FAQ</a>
                  </li>
                  <!--  -->
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#timelines">Timelines</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/facebook-timeline.html">Facebook Timeline</a></li>                                    
                <li><a tabindex="-1" href="pages/historical-timeline.html">Historical Timeline</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#userprofiles">User Profiles</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/basic-user-profile.html">Basic User Profile</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#inbox">Inbox</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/chat-inbox.html">Chat Inbox</a></li>                                    
                <li><a tabindex="-1" href="pages/email-inbox.html">Email Inbox</a></li>                                    
                <li><a tabindex="-1" href="pages/email-inbox-preview-pane.html">Email Inbox with Preview Pane</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#business">Business</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/pricing-tables.html">Pricing Tables</a></li>                                    
                <li><a tabindex="-1" href="pages/contact-us.html">Contact Us</a></li>                                    
                <li><a tabindex="-1" href="pages/features-page.html">Features Page</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#blog">Blog</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/blog-category.html">Blog Category</a></li>                                    
                <li><a tabindex="-1" href="pages/blog-page.html">Blog Page</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#errorpages">Error pages</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/404-page.html">404 Page</a></li>                                    
                <li><a tabindex="-1" href="pages/500-page.html">500 Page</a></li></ul>
              </li>
                                                                        <li class="dropdown-submenu">
                <a tabindex="-1" href="#shop">Shop</a>
                <ul class="dropdown-menu">                                    
                <li><a tabindex="-1" href="pages/shop-category.html">Shop Category</a></li>                                    
                <li><a tabindex="-1" href="pages/shop-index.html">Shop Index</a></li></ul>
              </li>
                        <!-- BEGIN MORE OPTIONS -->
      <li class="dropdown-submenu">
        <a tabindex="-1" href="#">More options</a>
        <ul class="dropdown-menu">
          <li><a tabindex="-1" href="#">Second level link</a></li>
          <li><a tabindex="-1" href="#">Second level link</a></li>
          <li class="dropdown-submenu">
            <a tabindex="-1" href="#">More options</a>
            <ul class="dropdown-menu">
              <li><a tabindex="-1" href="#">Third level link</a></li>
              <li><a tabindex="-1" href="#">Third level link</a></li>
              <li><a tabindex="-1" href="#">Third level link</a></li>
            </ul>
          </li>
          <li><a tabindex="-1" href="#">Second level link</a></li>
        </ul>
      </li>
      <!-- END MORE OPTIONS -->
            </ul>
    </li>
<!--  -->        </ul>
        <ul class="nav social-sm-nav">
        <li class="dropdown social-sm-fullwidth">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Super Menu<b class="caret"></b> </a>
  <ul class="dropdown-menu">
    <li class="social-sm-content">
      <div class="row-fluid">
        <div class="alert alert-error span12">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <strong>Oh snap!</strong> Change a few things up and try submitting again.
        </div>
      </div>

      <div class="row-fluid">
        <a href="#" class="icon-btn icon-btn-blue span3">
          <i class="icon-dashboard icon-2x"></i>
          <div>Dashboard</div>
          <span class="badge label-warning">2</span>
        </a>
        <a href="#" class="icon-btn span3">
          <i class="icon-calendar icon-2x"></i>
          <div>Calendar</div>
          <span class="badge label-important">4</span>
        </a>
        <a href="#" class="icon-btn icon-btn-green span3">
          <i class="icon-inbox icon-2x"></i>
          <div>Inbox</div>
          <span class="badge label-success badge-right">2</span>
        </a>
        <a href="#" class="icon-btn icon-btn-orange span3">
          <i class="icon-money icon-2x"></i>
          <div>Finances</div>
          <span class="badge  label-info badge-right">256$</span>
        </a>
      </div>

      <div class="row-fluid">
        <div class="span5">
          <h4><strong>Recent messages</strong></h4>
          <div class="media">
            <a class="pull-left" href="#">
              <img class="media-object" src="../assets/img/people-face/user1_55.jpg" alt="64x64">
            </a>
            <div class="media-body">
              <small class="pull-right">Just Now</small>
              <h4 class="media-heading">Yadra Abels</h4>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio.
            </div>
          </div>
          <div class="media">
            <a class="pull-left" href="#">
              <img class="media-object" src="../assets/img/people-face/user2_55.jpg" alt="64x64">
            </a>
            <div class="media-body">
              <small class="pull-right">Yesterday</small>
              <h4 class="media-heading">Cesar Mendoza</h4>
              Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo.
            </div>
          </div>
        </div>
        <div class="span7">
          <h4><strong>Tasks</strong></h4>
          <div>
            <strong>Prepare Report</strong><span class="pull-right">30%</span>
            <div class="progress progress-danger active">
                <div class="bar" style="width: 30%;"></div>
            </div>
          </div>

          <div>
            <strong>Fix critical bugs</strong><span class="pull-right">80%</span>
            <div class="progress progress-striped active">
                <div class="bar" style="width: 80%;"></div>
            </div>
          </div>

          <div>
            <strong>Complete project</strong><span class="pull-right">5%</span>
            <div class="progress progress-success active">
                <div class="bar" style="width: 5%;"></div>
            </div>
          </div>

        </div>
      </div>

    </li>
  </ul>
</li>        </ul>
        
        <!-- BEGIN NAVBAR INDICATORS -->
         <ul class="nav pull-right nav-indicators">
                      
            <!-- BEGIN DROPDOWN NOTIFICATIONS -->
            <li class="dropdown nav-notifications">
              <!-- BEGIN DROPDOWN TOGGLE -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="badge">9</span><i class="icon-warning-sign"></i>
              </a>
              <!-- END DROPDOWN TOGGLE -->
              <!-- BEGIN DROPDOWN MENU -->
              <ul class="dropdown-menu">
                <!-- BEGIN DROPDOWN HEADER -->
                <li class="nav-notifications-header">
                  <a tabindex="-1" href="#">You have <strong>9</strong> new notifications</a>
                </li>
                <!-- END DROPDOWN HEADER -->
                <!-- BEGIN NOTIFICATION ITEMS -->
                                  <li class="nav-notification-body text-info">
                    <a href="#">
                          <i class="icon-user"></i> New User
                          <small class="pull-right">Just Now</small>
                    </a>
                  </li>
                  <li class="nav-notification-body text-error">
                    <a href="#">
                          <i class="icon-user"></i> User Deleted
                          <small class="pull-right">Just Now</small>
                    </a>
                  </li>
                  <li class="nav-notification-body text-warning">
                    <a href="#">
                          <i class="icon-cogs"></i> Sever is overloaded
                          <small class="pull-right">2 minutes ago</small>
                    </a>
                  </li>
                  <li class="nav-notification-body">
                    <a href="#">
                          <i class="icon-briefcase"></i> Backup is completed
                          <small class="pull-right">4 minutes ago</small>
                    </a>
                  </li>
                                  <li class="nav-notification-body text-info">
                    <a href="#">
                          <i class="icon-user"></i> New User
                          <small class="pull-right">Just Now</small>
                    </a>
                  </li>
                  <li class="nav-notification-body text-error">
                    <a href="#">
                          <i class="icon-user"></i> User Deleted
                          <small class="pull-right">Just Now</small>
                    </a>
                  </li>
                  <li class="nav-notification-body text-warning">
                    <a href="#">
                          <i class="icon-cogs"></i> Sever is overloaded
                          <small class="pull-right">3 minutes ago</small>
                    </a>
                  </li>
                  <li class="nav-notification-body">
                    <a href="#">
                          <i class="icon-briefcase"></i> Backup is completed
                          <small class="pull-right">6 minutes ago</small>
                    </a>
                  </li>
                                <!-- END NOTIFICATION ITEMS -->
                <!-- BEGIN DROPDOWN FOOTER -->
                <li class="nav-notifications-footer">
                  <a tabindex="-1" href="#">View all messages
                  </a>
                </li>
                <!-- END DROPDOWN FOOTER -->
              </ul>
              <!-- END DROPDOWN MENU -->
            </li>
            <!-- END DROPDOWN NOTIFICATIONS -->

            <!-- BEGIN DROPDOWN TASKS -->
            <li class="dropdown nav-tasks">
              <!-- BEGIN DROPDOWN TOGGLE -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="badge">13</span>
                <i class="icon-tasks"></i>
              </a>
              <!-- END DROPDOWN TOGGLE -->
              <!-- BEGIN DROPDOWN MENU -->
              <ul class="dropdown-menu">
                <!-- BEGIN DROPDOWN HEADER -->
                <li class="nav-taks-header">
                  <a tabindex="-1" href="#">You have <strong>13</strong> tasks in progress</a>
                </li>
                <!-- END DROPDOWN HEADER -->
                <!-- BEGIN DROPDOWN ITEMS -->
                <li>
                  <a>
                    <strong>Prepare Report</strong><span class="pull-right">30%</span>
                    <div class="progress progress-danger active">
                        <div class="bar" style="width: 30%;"></div>
                    </div>
                  </a>
                </li>
                <li>
                  <a>
                    <strong>Make new update</strong><span class="pull-right">40%</span>
                    <div class="progress progress-info active">
                        <div class="bar" style="width: 40%;"></div>
                    </div>
                  </a>
                </li>
                <li>
                  <a>
                    <strong>Fix critical bugs</strong><span class="pull-right">80%</span>
                    <div class="progress progress-striped active">
                        <div class="bar" style="width: 80%;"></div>
                    </div>
                  </a>
                </li>
                <li>
                  <a>
                    <strong>Complete project</strong><span class="pull-right">5%</span>
                    <div class="progress progress-success active">
                        <div class="bar" style="width: 5%;"></div>
                    </div>
                  </a>
                </li>
                <li>
                  <a>
                    <strong>Others</strong><span class="pull-right">15%</span>
                    <div class="progress progress-warning active">
                        <div class="bar" style="width: 15%;"></div>
                    </div>
                  </a>
                </li>
                <!-- END DROPDOWN ITEMS -->
                <!-- BEGIN DROPDOWN FOOTER -->
                <li class="nav-taks-footer">
                  <a tabindex="-1" href="#">View all tasks
                  </a>
                </li>
                <!-- END DROPDOWN FOOTER -->
              </ul>
              <!-- END DROPDOWN MENU -->
            </li>
            <!-- END DROPDOWN TASKS -->

            <!-- BEGIN DROPDOWN MESSAGES -->
            <li class="dropdown nav-messages">
              <!-- BEGIN DROPDOWN TOGGLE -->
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="badge">8</span>
                <i class="icon-envelope"></i>
              </a>
              <!-- END DROPDOWN TOGGLE -->
              <!-- BEGIN DROPDOWN MENU -->
              <ul class="dropdown-menu">
                <!-- BEGIN DROPDOWN HEADER -->
                <li class="nav-messages-header">
                  <a tabindex="-1" href="#">You have <strong>8</strong> new messages</a>
                </li>
                <!-- END DROPDOWN HEADER -->
                <!-- BEGIN DROPDOWN ITEMS -->
                                                <li class="nav-message-body">
                  <a>
                      <img src="../assets/img/people-face/user1_55.jpg" alt="User">
                      <div>
                        <small class="pull-right">Just Now</small>
                        <strong>Yadra Abels</strong>
                      </div>
                      <div>
                        Lorem ipsum dolor sit amet, consectetur...
                      </div>
                  </a>
                </li>
                                <li class="nav-message-body">
                  <a>
                      <img src="../assets/img/people-face/user2_55.jpg" alt="User">
                      <div>
                        <small class="pull-right">Just Now</small>
                        <strong>Cesar Mendoza</strong>
                      </div>
                      <div>
                        Lorem ipsum dolor sit amet, consectetur...
                      </div>
                  </a>
                </li>
                                <li class="nav-message-body">
                  <a>
                      <img src="../assets/img/people-face/user3_55.jpg" alt="User">
                      <div>
                        <small class="pull-right">Just Now</small>
                        <strong>John Doe</strong>
                      </div>
                      <div>
                        Lorem ipsum dolor sit amet, consectetur...
                      </div>
                  </a>
                </li>
                                <li class="nav-message-body">
                  <a>
                      <img src="../assets/img/people-face/user4_55.jpg" alt="User">
                      <div>
                        <small class="pull-right">Just Now</small>
                        <strong>Tobei Tsumura</strong>
                      </div>
                      <div>
                        Lorem ipsum dolor sit amet, consectetur...
                      </div>
                  </a>
                </li>
                                <!-- END DROPDOWN ITEMS -->
                <!-- BEGIN DROPDOWN FOOTER -->
                <li class="nav-messages-footer">
                  <a tabindex="-1" href="pages/chat-inbox.html">View all messages
                  </a>
                </li>
                <!-- END DROPDOWN FOOTER -->
              </ul>
              <!-- END DROPDOWN MENU -->
            </li>
            <!-- END DROPDOWN MESSAGES -->

            <li class="divider-vertical"></li>
            <!-- BEGIN EXTRA DROPDOWN -->
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-caret-down"></i></a>
              <ul class="dropdown-menu">
                <li><a href="pages/basic-user-profile.html"><i class="icon-user"></i> My Profile</a></li>
                <li><a href="#"><i class="icon-cogs"></i> Settings</a></li>
                <li><a href="login.html"><i class="icon-off"></i> Log Out</a></li>
                <li class="divider"></li>
                <li><a href="pages/faq.html"><i class="icon-info-sign"></i> Help</a></li>
                              </ul>
            </li>
            <!-- END EXTRA DROPDOWN -->
         </ul>
        <!-- END NAVBAR INDICATORS -->
        <!-- BEGIN PANEL TEMPLATE SETTINGS TRIGGER -->
        <ul class="nav pull-right hidden-phone">
          <!-- BEGIN DEMO SETTINGS -->
          <li id="demo-setting" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="icon-cog"></i>
            </a>
            <ul class="dropdown-menu settings">
              <li class="text-left">
                <a href="/">
                  Configurações Gerais
                </a>
              </li>
              <li class="divider"></li>
              <li class="header">Página inicial</li>
              <li class="text-left"><a href="/">Conteúdo 1</a></li>
              <li class="text-left"><a href="/">Conteúdo 2</a></li>
              <li class="text-left"><a href="/">Utilitários</a></li>
              <li class="text-left"><a href="/">Acesso rápido</a></li>
              <li class="text-left"><a href="/">Newsletter</a></li>
              <li class="text-left"><a href="/">Informativos/comunicados</a></li>
              <li class="text-left"><a href="/">Agenda tributária</a></li>
              
              <li class="divider"></li>
              <li class="header">Outras páginas</li>
              <li class="text-left"><a href="/">Empresa(Quem somos?)</a></li>
              <li class="text-left"><a href="/">Serviços</a></li>
              <li class="text-left"><a href="/">Clientes</a></li>
              <li class="text-left"><a href="/">Parceiros</a></li>
              
              
            </ul>
          </li>
          <!-- END DEMO SETTINGS -->
        </ul>
        <!-- END PANEL TEMPLATE SETTINGS TRIGGER -->
     </div>
   </div>
 </nav>
        <!-- END NAVBAR -->
      </header>
      
      <?php echo $this->content; ?>
      
    </div>
    <!-- END WRAPER -->
        
    <!-- BEGIN SIDEBAR PANEL -->
    <div style="display: none;">
      <ul class="rightPanel">
        <li>
          <a href="pages/basic-user-profile.html">
            <i class="icon-user"></i><span>My Profile</span>
          </a>
        </li>
        <li>
          <a href="pages/chat-inbox.html">
            <i class="icon-envelope"></i><span>Messages</span>
	  </a>
        </li>
        <li>
          <a href="#">
	    <i class="icon-tasks"></i><span>Taks</span>
	  </a>
	</li>
      </ul>
    </div>
    <!-- END SIDEBAR PANEL -->

    <!-- BEGIN JAVASCRIPT CODES -->
        <!-- BEGIN GENERAL JAVASCRIPT CODE -->
        <?php echo $this->headScript()
                        ->prependFile($this->basePath() . '/assets/js/dashboard.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.pulsate/jquery.pulsate.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/bootstrap.daterangepicker/daterangepicker.js')
                        ->prependFile($this->basePath() . '/assets/plugins/bootstrap.daterangepicker/moment.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.gritter/jquery.gritter.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.justgage/justgage.1.0.1.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.justgage/raphael.2.1.0.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.sparkline/jquery.sparkline.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.flot/jquery.flot.selection.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.flot/jquery.flot.resize.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.flot/jquery.flot.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.jqvmap/data/jquery.vmap.sampledata.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.jqvmap/maps/jquery.vmap.world.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.jqvmap/jquery.vmap.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.fullcalendar/fullcalendar.min.js')
                        ->prependFile($this->basePath() . '/assets/js/sidebar.js')
                        ->prependFile($this->basePath() . '/assets/js/demo-settings.js')
                        ->prependFile($this->basePath() . '/assets/js/app.js')
                        ->prependFile($this->basePath() . '/assets/js/extents.js')
                        ->prependFile($this->basePath() . '/assets/js/chatboxManager.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.livefilter/jquery.liveFilter.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.ui.chatbox/jquery.ui.chatbox.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.uipro/uipro.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.simplecolorpicker/jquery.simplecolorpicker.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.cookie/jquery.cookie.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.slimscroll/jquery.slimscroll.min.js')
                        ->prependFile($this->basePath() . '/assets/plugins/twitter-bootstrap/bootstrap.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.ui.touch-punch/jquery.ui.touch-punch.js')
                        ->prependFile($this->basePath() . '/assets/plugins/jquery.ui/jquery-ui-1.10.1.custom.min.js')
                        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'); ?>

        <!--[if lte IE 8]><script language="javascript" type="text/javascript" src="/templates/social/assets/plugins/jquery.flot/excanvas.min.js"></script><![endif]-->

        <script>window.jQuery || document.write('<script src="../assets/plugins/jquery/jquery.min.js"><\/script>')</script>

      <script>
        /*<![CDATA[*/
        $(function() {
          App.init();
            DemoSettings.init({ urlThemes: '../assets/css/themes/social.theme-'});
          SideBar.init({shortenOnClickOutside: false});
        });
        /*]]>*/
      </script>
    <!-- END GENERAL JAVASCRIPT CODE -->

    <!-- BEGIN JAVASCRIPT CODES FOR THE CURRENT PAGE -->
    

    <script>
      $(function() {
        var urlAvatar = "../assets/img/avatar-55.png";
          Dashboard.init({urlAvatar:urlAvatar});
        });
      </script>
    <!-- END JAVASCRIPT CODES FOR THE CURRENT PAGE -->
        <!-- END JAVASCRIPT CODES -->
    
    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='../../../../www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>

    <?php echo $this->inlineScript() ?>
  </body>


</html>